### ISSUE TITLE
GPL but lacking the license file

### ISSUE THREAD

**Issue by ornicar** [abebinder/memchess#62]
Hi, thanks for memchess!

It should be released as GPL software because it bundles [chessground](https://github.com/lichess-org/chessground). Please see [licensing details](https://github.com/lichess-org/chessground#license)

All you need to do is add LICENSE file at the root of the repository. You can copy the [chessground license file](https://github.com/lichess-org/chessground/blob/master/LICENSE)

**Comment by abebinder** [comment]
@ornicar 

* Done and sorry I originally forgot to do this.
* Thank you for your work on the repositories which I am using for this project: chessground and chess-openings.
* Thank you for lichess. [I play on it almost every day.](https://lichess.org/@/fxhasthemovies)
